# Generated by Django 5.2.6 on 2025-09-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='task',
            name='key',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('user', 'key')},
        ),
    ]
