# Generated by Django 5.2.6 on 2025-10-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_unique_together_alter_task_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
