# Generated by Django 5.2.6 on 2025-10-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
